name: Base44 Cron Jobs

on:
  schedule:
    - cron: '*/10 * * * *'  # Process Scheduled Emails - Every 10 minutes
    - cron: '*/15 * * * *'  # Process Email Automations - Every 15 minutes
    - cron: '*/30 * * * *'  # Check Cadence Replies - Every 30 minutes
    - cron: '0 * * * *'     # Process Report Schedules - Every hour

  workflow_dispatch:

jobs:
  process-scheduled-emails:
    runs-on: ubuntu-latest
    steps:
      - name: Call processScheduledEmails function
        run: |
          curl -X POST \
          https://6853c86e704151cd98ca0a3e.base44.app/functions/processScheduledEmails \
          -H 'Content-Type: application/json' \
          -d '{}'

  process-email-automations:
    runs-on: ubuntu-latest
    steps:
      - name: Call processEmailAutomations function
        run: |
          curl -X POST \
          https://6853c86e704151cd98ca0a3e.base44.app/functions/processEmailAutomations \
          -H 'Content-Type: application/json' \
          -d '{}'

  check-cadence-replies:
    runs-on: ubuntu-latest
    steps:
      - name: Call checkCadenceReplies function
        run: |
          curl -X POST \
          https://6853c86e704151cd98ca0a3e.base44.app/functions/checkCadenceReplies \
          -H 'Content-Type: application/json' \
          -d '{}'

  process-report-schedules:
    runs-on: ubuntu-latest
    steps:
      - name: Call processReportSchedules function
        run: |
          curl -X POST \
          https://6853c86e704151cd98ca0a3e.base44.app/functions/processReportSchedules \
          -H 'Content-Type: application/json' \
          -d '{}'
